# Generated by Django 5.2.8 on 2025-12-09 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_projetos', '0004_projeto_professor_responsavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('lider', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'Estudante'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_lideradas', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='api_projetos.projeto')),
            ],
        ),
    ]
